# -*- coding: utf-8 -*-
"""langchain60_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvgeehNJtP9qL99e2Uic42qJCM3BU9Aj
"""

import streamlit as st
import os
from dotenv import load_dotenv

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Load .env file
load_dotenv()

st.set_page_config(page_title="LangChain Chatbot", page_icon="🤖")

st.title("🤖 Chatbot with Runtime API Key (LangChain)")

# Get API key from environment
groq_api_key = os.getenv("GROQ_API_KEY")

# Step 2: Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Step 3: Display chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# Step 4: Take user input
if prompt := st.chat_input("Type your message..."):
    if not groq_api_key:
        st.error("⚠️ GROQ API key not found. Please check your .env file.")
    else:
        # Save user message
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # LangChain setup (Groq)
        llm = ChatGroq(
            model_name="llama-3.1-8b-instant",
            groq_api_key=groq_api_key,
        )

        prompt_template = ChatPromptTemplate.from_messages([
            ("system", "You are a helpful assistant."),
            ("user", "{question}")
        ])

        chain = prompt_template | llm | StrOutputParser()

        # Run chain
        bot_reply = chain.invoke({"question": prompt})

        # Save and display assistant message
        st.session_state.messages.append({"role": "assistant", "content": bot_reply})
        with st.chat_message("assistant"):
            st.markdown(bot_reply)